"""Initial schema

Revision ID: 88033088928e
Revises: 
Create Date: 2026-04-13 19:07:04.991625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88033088928e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_accidents_id'), table_name='accidents')
    op.drop_index(op.f('ix_accidents_segment_500m'), table_name='accidents')
    op.drop_index(op.f('ix_accidents_upload_id'), table_name='accidents')
    op.drop_table('accidents')
    op.drop_index(op.f('ix_blackspots_id'), table_name='blackspots')
    op.drop_index(op.f('ix_blackspots_segment_500m'), table_name='blackspots')
    op.drop_index(op.f('ix_blackspots_upload_id'), table_name='blackspots')
    op.drop_table('blackspots')
    op.drop_index(op.f('ix_alerts_blackspot_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_upload_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_segments_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_is_blackspot'), table_name='segments')
    op.drop_index(op.f('ix_segments_segment_500m'), table_name='segments')
    op.drop_index(op.f('ix_segments_upload_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_recommendations_blackspot_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_upload_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blackspot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rationale', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blackspot_id'], ['blackspots.id'], name=op.f('recommendations_blackspot_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('recommendations_upload_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('recommendations_pkey'))
    )
    op.create_index(op.f('ix_recommendations_upload_id'), 'recommendations', ['upload_id'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_blackspot_id'), 'recommendations', ['blackspot_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('segment_500m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_accidents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_fatal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_grievous', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_minor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_non_injured', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('years_active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accident_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dominant_nature', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dominant_cause', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('dominant_vehicle', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('dominant_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('locations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accident_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('severity_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fatal_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('grievous_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rate_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('criteria_a', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criteria_b', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criteria_c', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criteria_d', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criteria_e', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criteria_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_blackspot', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_watch_zone', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('risk_tier', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('blackspot_rank_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('segments_upload_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('segments_pkey'))
    )
    op.create_index(op.f('ix_segments_upload_id'), 'segments', ['upload_id'], unique=False)
    op.create_index(op.f('ix_segments_segment_500m'), 'segments', ['segment_500m'], unique=False)
    op.create_index(op.f('ix_segments_is_blackspot'), 'segments', ['is_blackspot'], unique=False)
    op.create_index(op.f('ix_segments_id'), 'segments', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blackspot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('segment_500m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_tier', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('weather_condition', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('triggered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blackspot_id'], ['blackspots.id'], name=op.f('alerts_blackspot_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('alerts_upload_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('ix_alerts_upload_id'), 'alerts', ['upload_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_blackspot_id'), 'alerts', ['blackspot_id'], unique=False)
    op.create_table('blackspots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('segment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('segment_500m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_accidents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_fatal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_grievous', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('accident_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('criteria_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('risk_tier', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('blackspot_rank_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dominant_cause', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('dominant_nature', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dominant_vehicle', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('dominant_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('locations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('blackspots_segment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('blackspots_upload_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('blackspots_pkey'))
    )
    op.create_index(op.f('ix_blackspots_upload_id'), 'blackspots', ['upload_id'], unique=False)
    op.create_index(op.f('ix_blackspots_segment_500m'), 'blackspots', ['segment_500m'], unique=False)
    op.create_index(op.f('ix_blackspots_id'), 'blackspots', ['id'], unique=False)
    op.create_table('accidents',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sr_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('location_chainage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('accident_location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nature', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('classification', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('causes', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('road_features', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('road_condition', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('intersection', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('weather', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vehicle_type', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('fatal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grievous', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('minor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('non_injured', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('chainage_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weekday', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('is_weekend', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_of_day', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('season', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('severity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('severity_label', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('segment_500m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('segment_1km', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('accidents_upload_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('accidents_pkey'))
    )
    op.create_index(op.f('ix_accidents_upload_id'), 'accidents', ['upload_id'], unique=False)
    op.create_index(op.f('ix_accidents_segment_500m'), 'accidents', ['segment_500m'], unique=False)
    op.create_index(op.f('ix_accidents_id'), 'accidents', ['id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('pipeline_started', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('pipeline_ended', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('record_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blackspot_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('segment_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('uploads_pkey'))
    )
    op.create_index(op.f('ix_uploads_id'), 'uploads', ['id'], unique=False)
    # ### end Alembic commands ###
